---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zabbix-oneview-shared
  namespace: zabbix
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: hpe-nimble-file